name: Build Docker Image

permissions:
  contents: read
  packages: write

on:
  workflow_call:
    inputs:
      target_tag:
        required: true
        type: string
      target_platform:
        default: linux/amd64
        type: string
      build_args:
        type: string
      force:
        default: false
        type: boolean

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Check if image exists
        id: image-exists
        if: ${{ !inputs.force }}
        uses: tyriis/docker-image-tag-exists@v2.1.0
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}
          tag: ${{ inputs.target_tag }}

      - name: Decide whether to build
        id: should-build
        run: |
          if [[ "${{ inputs.force }}" == "true" || "${{ steps.image-exists.outputs.tag }}" != "found" ]]; then
            echo "build=true" >> $GITHUB_OUTPUT
          else
            echo "build=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Hadolint
        if: ${{ steps.should-build.outputs.build == 'true' }}
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: ./Dockerfile
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true

      - name: Upload SARIF
        if: ${{ steps.should-build.outputs.build == 'true' && github.event_name == 'push' }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: hadolint-results.sarif

      - name: Set up Buildx
        if: ${{ steps.should-build.outputs.build == 'true' }}
        uses: docker/setup-buildx-action@v4

      - name: Login to GHCR
        if: ${{ steps.should-build.outputs.build == 'true' }}
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: ${{ steps.should-build.outputs.build == 'true' }}
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: ${{ inputs.target_platform }}
          push: true
          build-args: ${{ inputs.build_args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.IMAGE_NAME }}:${{ inputs.target_tag }}
            ${{ env.IMAGE_NAME }}:latest
